spring.application.name=mexotic

spring.datasource.url=jdbc:mysql://localhost:3306/mexoticTours?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Pa$$w0rd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8080
